<?php

namespace App\Constantes;

class Constantes
{
    const CATEGORIAS_CURSOS = [
        'Administración Pública',
        'Agronomía y Ciencias del Suelo',
        'Análisis de Datos y Ciencia de Datos',
        'Animación y Efectos Visuales (VFX)',
        'Arte y Creatividad',
        'Astrología y Espiritualidad',
        'Aviación y Pilotaje',
        'Ciencia y Tecnología',
        'Cocina y Gastronomía',
        'Construcción y Obras Civiles',
        'Criptomonedas y Blockchain',
        'Cuidado Animal y Veterinaria',
        'Cultura y Sociedad',
        'Cursos Especializados',
        'Cursos Relacionados con Tecnología Emergente',
        'Deportes y Actividades Físicas',
        'Desarrollo de Videojuegos',
        'Desarrollo web',
        'Desarrollo Personal',
        'Diseño UX/UI',
        'Diseño y Arquitectura',
        'Diversidad e Inclusión',
        'Educación Académica',
        'Educación Infantil',
        'Energías Renovables',
        'Escritura y Literatura',
        'Estudios Jurídicos y Derecho',
        'Finanzas y Contabilidad',
        'Formación Profesional',
        'Fotografía y Edición',
        'Gestión del Estrés y Resiliencia',
        'Gestión de Proyectos',
        'Habilidades para la Vida (Life Skills)',
        'Habilidades Técnicas Industriales',
        'Historia del Arte y la Cultura',
        'Hobby y Entretenimiento',
        'Idiomas',
        'Innovación y Creatividad Empresarial',
        'Inteligencia Artificial',
        'Jardinería y Paisajismo',
        'Logística y Cadena de Suministro',
        'Manualidades y DIY (Hazlo Tú Mismo)',
        'Marketing y Publicidad',
        'Medio Ambiente y Sustentabilidad',
        'Moda y Estilo',
        'Música y Producción Musical',
        'Negocios y Emprendimiento',
        'Pesca y Actividades al Aire Libre',
        'Preparación Física para Competencias Deportivas',
        'Preparación para Exámenes',
        'Preparación para la Jubilación',
        'Primeros Auxilios y Salud Pública',
        'Producción de Contenidos para Redes Sociales',
        'Realidad Aumentada y Virtual',
        'Relaciones Humanas y Coaching',
        'Religión y Filosofía',
        'Resolución de Problemas y Toma de Decisiones',
        'Robótica y Automatización',
        'Salud y Bienestar',
        'Seguridad y Defensa',
        'Técnicas de Enseñanza y Formación',
        'Técnicas de Oratoria y Presentación',
        'Tecnología y Programación',
        'Terapias Alternativas y Holísticas',
        'Viajes y Turismo'
    ];

    const ESTADOS_CURSO = [
        'En revisión',
        'Aprobado',
        'Cancelado',
        'Pausado',
        'Eliminado',
        'En mantenimiento',
    ];

    const ROLES_USUARIO = [
        'superadmin',
        'administrador',
        'instructor',
        'alumno',
    ];
}
